pipeline {
    agent any

    stages {

       stage('Git Checkout'){
            
            steps{
                
                script{
                    
                    git branch: 'main', url: 'https://github.com/mohamedrafi13/devopsintproject.git'
                }
            }
        }
        stage('sonar quality check') {
            agent {
                docker {
                    image 'maven'
                }
            }
            steps{
                script{
                    withSonarQubeEnv(credentialsId: 'deekshithSN') {
                        'mvn clean package sonar:sonar'
                    }
                }
            }
        }
        stage('Quality gate Status') {
            steps{
                script{
                    waitForQualityGate abortPipeline: false, credentialsId: 'deekshithSN'
                }
            }
        }
/*      stage('Docker Build & Push to Docker Repo') {
            steps{
                script{
                    
                }
            }
        } */
    }
}